language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.10.3
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q coverage
  - python setup.py -q install
# command to run tests
script: coverage run --source=django_cmdlog --omit="*/test/*.py" setup.py test
after_success:
  - pip install python-coveralls
  - coveralls
